### ISSUE TITLE
issue with getPopulationAgeGroup

### ISSUE THREAD

**Issue by seah-kjs** [jolene-lim/onemapsgapi#1]
"getPopulationAgeGroup" with gender=NULL will return gender="Total" for all total, male and female rows. 

It is likely due to the function `get_pop_query`:

`
else if (!(data_type %in% c("getEthnicGroup", "getPopulationAgeGroup") & !is.null(gender))) {
output <- output %>% mutate(gender = 'Total')
}
`

**Comment by jolene-lim** [comment]
Hi there @seah-kjs! Based on the [onemapsg api docs](https://www.onemap.gov.sg/docs/#population-query):

|  gender | Based on gender {male or female}. Returns all results by default. |
|---|---|

Hence, it is accurate for gender = Total to be returned even if the input parameter was gender = NULL. Hope this clarifies, happy to review this if its causing any issues

**Comment by seah-kjs** [comment]
pls run the following, the gender column should be "male", "female", "total" instead of "total", "total", "total"??? else it wont differentiate male and female? thanks.

<img width="935" alt="Screenshot 2022-09-27 at 20 38 18" src="https://user-images.githubusercontent.com/51918300/192528778-1c6cc271-6421-4786-89ee-1ff25d39679a.png">

**Comment by jolene-lim** [comment]
@seah-kjs thanks for sharing, bug should be fixed in the github version now (install instructions below) - will take a while more to get the changes up in CRAN. for your script which seems to be querying one data type, year and planning area, you can also now use the `get_pop_query` function that has been exported. thanks!

```
# install.packages("devtools")
devtools::install_github("jolene-lim/onemapsgapi")
```
